### ISSUE TITLE
Several Issues with FT 3Alpha

### ISSUE THREAD

**Issue by tomheaps** [formtools/core#106]
Seriously impressed with this piece of coding.

I have successfully managed to install FT 3 Alpha on my server (Litespeed) however whilst playing around with it I have come across several issues:

1) Client Map Filter View not saving - when creating a client map filter view e.g. linking the information in a specific form filed to a client's surname when I click on update view I get the usual blue box confirming that the view has been updated however when I go back into this form an look under views, the client map filter view has not been saved / added to the form and is not active when viewing submissions as a client. The Standard Filters however seem to be saving and working fine

2) System Check errors - when I run the system check module immediately after installation of Form Tools I get the following errors under File Verification: 

```
Form Tools Core: FAIL. Missing files
- .gitignore

Data Visualization: FAIL. Missing files
- modules/data_visualization/code/FIeldCharts.class.php 
```

3) Error in Download / Export function - when I try to display a html export of submissions for any form I get the error message regarding incorrect path to the themes/cache folder or incorrect read-write permissions. Going into the themes folder on my server, it appears that no cache folder was ever generated during the installation of FT. I have manually added a folder called cache and set its permissions to 777 - now I can display an HTML export of form submissions for printing but when I try to generate an Excel export of submissions, the file that downloads is a .html file and not a .xls spreadsheet!

4) Unable to create a new Hook - when I try to create a new hook using the Hooks Manager I get a 403 error (access denied) message from my server. Don't know if this is something relating to a specific folders read-write permissions - not sure which folder the hooks are being saved in??

5) Error when trying to access multiple modules - when I try to open certain modules (e.g. Submission Pre-parser and Text Override) I get the following error message 

```
Fatal error: Uncaught --> Smarty: Unable to load template 'file:messages.tpl' in '/home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/submission_pre_parser/templates/index.tpl' <-- thrown in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 185`
```
I have checked that I have the latest versions of these modules installed i.e. 2.0.0 which should be compatible with Form Tools 3?
Thanks for your help.

**Comment by benkeen** [comment]
@tomheaps - fantastic, thanks for the bug report! Just off to work but I'll get back to you tonight.

**Comment by benkeen** [comment]
Hey @tomheaps, sorry for the wait. Notes below:

> 1. Client Map Filter View not saving
Thanks for letting me know! This has been patched in today's core build (3.0.0-alpha-20171122). 

> 2. System Check errors.
Don't worry - both issues were benign, but I've patched them both. Be sure to update the Data Visualization module to fix that particular issue. 

> 3. Error in Download / Export function
All fixed - just download the latest version of the Export Manager. Sorry, I'd introduced this issue in a recent version of the Core. 

> 4. Unable to create a new hook 
Curious! I wasn't able to reproduce this - seems to work fine on my end. Hooks are actually all just stored in the database, so I'm wondering if maybe that error you're spotted was also caused by the core issue I just patched. Mind updating your various component from the latest alpha [https://formtools.org/download/alpha.php] and seeing if this problem still exists?

Thanks again, @tomheaps - keep the bug reports coming! ;-) 

Ben

**Comment by tomheaps** [comment]
Thanks Ben.

**1) Client Map Filter is now saving OK** however when you click on Update View, a load of code gets printed at the top of the page:

> Array ( [view_id] => 2 [view_name] => User View [num_submissions_per_page] => 10 [default_sort_field] => submission_date [default_sort_field_order] => desc [access_type] => public [may_delete_submissions] => no [may_add_submissions] => yes [field_id_1] => 7 [is_sortable_1] => on [auto_size_1] => on [truncate_1] => truncate [field_id_2] => 5 [is_sortable_2] => on [auto_size_2] => on [truncate_2] => truncate [field_id_3] => 3 [is_sortable_3] => on [auto_size_3] => on [truncate_3] => truncate [field_id_4] => 4 [is_sortable_4] => on [auto_size_4] => on [truncate_4] => truncate [may_edit_submissions] => yes [deleted_groups] => [group_name_16] => Data [group_tab_16] => 1 [searchable_fields] => Array ( [0] => 7 [1] => 8 [2] => 3 [3] => 4 [4] => 5 [5] => 6 ) [tabs] => Array ( [0] => Data [1] => [2] => [3] => [4] => [5] => ) [num_standard_filters] => 1 [num_client_map_filters] => 1 [standard_filter_1_field_id] => [standard_filter_1_operator_date] => before [standard_filter_1_operator] => equals [standard_filter_1_filter_date_values] => [standard_filter_1_filter_values] => [num_standard_filter_rows] => 1 [client_map_filter_1_field_id] => 2 [client_map_filter_1_operator] => equals [client_map_filter_1_client_field] => last_name [num_client_map_filter_rows] => 1 [update_view] => Update View [view_fields_sortable__rows] => 16|7,8,3,4,5,6 [view_fields_sortable__new_groups] => 7,8,3,4,5,6 [view_fields_sortable__deleted_rows] => [submission_list_sortable__rows] => 1,2,3,4 [submission_list_sortable__new_groups] => 1,2,3,4 [submission_list_sortable__deleted_rows] => [form_id] => 1 [view_fields_sortable_id] => view_fields [submission_list_sortable_id] => submission_list )

**2. Please see point number 5 in my original post above** - I think you may have missed this one first time around? The problem is still persisting and is now affecting even more modules since your patch - I get the same error now when trying to run the System Check module as well as Submission Pre-parser and Text Override modules:

> Fatal error: Uncaught --> Smarty: Unable to load template 'file:messages.tpl' in '/home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/submission_pre_parser/templates/index.tpl' <-- thrown in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 185

So can't check whether the system check is passing now since your patch....

**3. Error in Download / Export function** - still persists i.e. when you click on generate to create an excel file, a html file is downloaded instead - when I go into the export manager module itself and look at the export types tab only 'table format' is listed suggesting that the export to excel function has not been installed?

**4. I am still unable to create a hook** - getting a 403 access denied error when I am trying to create the hook that you described in [this forum post](https://forums.formtools.org/showthread.php?tid=1902&highlight=Add+client+name) to add client name to all new submissions. Should the PHP code contain the credentials for logging into the database (database name, host, username, password) or is this automatically generated by FT?

**Comment by benkeen** [comment]
Hey @tomheaps. Drat, sorry about issue 1 - that's what happens when you rush...! The code printout at the top of the page was just some debugging code I'd left in. Today's update of the core (https://formtools.org/download/alpha.php) includes a fix for both that and the serious error that you see when logging in as a client. Thanks for letting me know about that.

Regarding 2, I'd refactored the themes with 3.0.0 to remove a whole bunch of duplicate code: now they all inherit various files from the default theme if they haven't been overridden, include that messages file. The Submission Pre-Parser + Text Override modules just hadn't been updated to include the way of dynamically referencing those file. Both have been updated to include the fix: just download the latest release.
https://github.com/formtools/module-text_override/releases
https://github.com/formtools/module-submission_pre_parser/releases

I suspect the System Check module also has that problem - I'll patch it shortly. As a temporary workaround, use the default theme. That should circumvent the issue.

For issue 3, sorry I should have been more clear on this one: you'll need to uninstall and re-install the Export Manager module to get the latest settings (just click "uninstall", then "install" on the Modules page - it won't remove the files). After that, files will then be generated with a `.xls` format, but just FYI, the file content is in fact still HTML (!). The important thing is the file extension - Excel / Open Office will both know how to read the file contents.

For issue 4, I'll get back to you - ran out of time tonight. 

All the best!

**Comment by tomheaps** [comment]
Thanks. Most issues now resolved. Still struggling with Hooks Manager though. I could work around this issue by using Submissions Pre-Parser which doesn't seem to be causing the same 403 error but I am stuck. What php code (PHP 5.6) would I need to write into the Submissions Pre-Parser so that every time I submit a new form, a form field e.g. 'user_email' is automatically filled in with the currently logged in user's email (so I can then apply a custom map filter so users can only view forms they have completed)?

Would you consider adding in functionality to achieve this easily when creating a form e.g. have an automatic field option that you can set to user name, email, id etc - this seems to be a popular request amongst forum users....

Thanks so much for your time.

**Comment by benkeen** [comment]
Heya, sorry for not getting back to you sooner. 

I'm just not sure about the 403 error... I haven't been able to see the problem to debug, and I can't think what would be causing it.

But yes, ultimately I think the Client Map filters are a bit poorly designed and need improvements. But I can't take on any changes to the script until FT3 is finally released - I have _faaar_ too much work to do to just get to that stage, let alone any other work. Sorry about that. :(

**Comment by tomheaps** [comment]
No worries, I have found a work around for now by adjusting the code directly in the submissions.php file. 

Do you want me to let you know if I find any more bugs?
