### ISSUE TITLE
Themes cache RW access on Fedora/Centos

### ISSUE THREAD

**Issue by massimoantoniello** [formtools/core#151]
Hi,

I've read all posts on the forum and info but still unable to install the formtools that on paper looks fantastic for my need.

Initially tried on ubuntu 16.4 ( but PHP7.0 show stopper was to complex to overcome )
I've then  tried also on a fresh new Fedora and also CentOs with all LAMP components and PHP 5.6 

These machines were local HW installed and with all privileges on files and directory set I've installed the latest 2.2 version of formtools.

But on all configurations I keep on getting the message on themes/cache directory not read/writable, I've tried to change the owner to nobody, used chmod -R 777 command on cache then also on entire web directory tree but without any results, I've also browse the code to relax the checks with no benefit, I'm getting crazy there should be an easy explanation.

Thanks anybody will support me and greetings from Italy
Massimo

**Comment by benkeen** [comment]
Hey from Vancouver, BC!

Sorry you're having trouble, what a pain. Couple of questions:
- Did you try both Form Tools 2 and 3? Or is this problem just occurring with Form Tools 2?
- What's the exact message that gets displayed? Could you post a screenshot? 

You mention the message is appearing on the `themes/cache` folder but it should actually be trying to set permissions on `themes/default/cache` (or `themes/[other theme]/cache`) so that's kind of odd... not sure why it would be omitting the theme folder.

**Comment by massimoantoniello** [comment]
From a brand new installed Fedora24 with LAMP component
Downloaded from www.formtools.org download FormTool2
Extracted in /var/www/html
CD into /var/www/html/formtools/themes/default/
SUDO chmod -R 777 cache
From browser localhost/formtools

Then I get 
" Before continuing, you will need to update your /themes/default/cache folder to allow full read and write permissions. Once this is done, this message will disappear and you can install the script. "

Thanks for kind reply,
Massimo

**Comment by massimoantoniello** [comment]
Hi Ben,

Here are the steps I followed:

From a brand new installed Fedora24 with LAMP component
Downloaded from www.formtools.org <http://www.formtools.org/> download FormTool2
Extracted in /var/www/html
CD into /var/www/html/formtools/themes/default/
SUDO chmod -R 777 cache
From browser localhost/formtools

Then I get a web page release 2.2.5 with this text:   " Before continuing, you will need to update your /themes/default/cache folder to allow full read and write permissions. Once this is done, this message will disappear and you can install the script. "

Thanks for kind reply,
Massimo

——


On 22 Feb 2018, at 15:57, Benjamin Keen <notifications@github.com> wrote:

Hey from Vancouver, BC!

Sorry you're having trouble, what a pain. Couple of questions:

Did you try both Form Tools 2 and 3? Or is this problem just occurring with Form Tools 2?
What's the exact message that gets displayed? Could you post a screenshot?
You mention the message is appearing on the themes/cache folder but it should actually be trying to set permissions on themes/default/cache (or themes/[other theme]/cache) so that's kind of odd... not sure why it would be omitting the theme folder.

**Comment by massimoantoniello** [comment]
Could it be that PHP.INI or APACHE configuration has some default setting to prevent accessing directories ?

**Comment by massimoantoniello** [comment]
Hi Ben,

The system is on a local dedicated PC not hosted and I face same problem with either FEDORA and CENTOS

I finally was able to FIX that by executing the following command:

chcon --type httpd_sys_rw_content_t cache

Reading the forum looks like others encounter same problem, maybe you can add that tips in the error message to avoid people to spend hours trying to execute chmod 777 cache ?

Kind Regards,
Massimo

**Comment by benkeen** [comment]
Excellent, I'm glad you got it sorted out! Yes, I'll include a note of this in the docs.

**Comment by benkeen** [comment]
Doc page added here: https://docs.formtools.org/installation/common_problems/

**Comment by jeff-12345** [comment]
I'm actually facing a similar issue installing the latest version of FormTools on Centos8:
I've gone through the setup process of FormTools, got all the way to Step 6 - Clean Up:
Congratulations, Form Tools has been successfully installed!.
However, after clicking "Login to Form Tools" it just give me the following message:

This page isn’t working
192.168.1.30 is currently unable to handle this request.
HTTP ERROR 500

I've verified that my MySQL is working fine, my PHP is working fine with the test info.php page, and my phpMyAdmin is working fine.  Logging into phpMyadmin, I see that it formtools had added a bunch of extra items to my database with the assigned prefix specified during setup, so I know it's connecting and communicating with mysql.

Why is form tools still giving me error code 500?
I've already set the proper file permissions as documented on Formtools web site regarding the cache and uploads folder to no avail.  This current version of Formtools does not have a "cache" folder within ./themes/defaults.
I had also tried the following command: chcon --type httpd_sys_rw_content_t cache
to no avail, so I disabled SELinux which that command corresponds to.  So that shouldn't be the problem.

My current setup:
CentOS 8 with SELinux disabled.
MySQL Server version: 5.7.32 - MySQL Community Server (GPL)
Apache/2.4.37 (centos)
PHP version: 7.2.24
phpMyAdmin Version 4.9.4,
I am also seeing this:
mysql -V  shows the following mysql Ver 14.14

Not sure if that could be causing the issue, because it is not even being used by phpMyAdmin.

Please advise.
Thanks,
