### ISSUE TITLE
Blank page on Formtools 3 beta

### ISSUE THREAD

**Issue by chakthy** [formtools/core#165]
I get a blank page when trying to run the installation script. There are no errors. On a similar issue with the previous version it was mentioned that the PHP version was the root cause, but the new one is compatible with PHP7 so that shouldn't be the root cause this time. Any ideas on how to fix it?

**Comment by chakthy** [comment]
On chrome I get a 500 internal server error

**Comment by benkeen** [comment]
Hi @chakthy, hmm! I just checked out the latest beta and noticed the cache folder was accidentally removed [it's normally empty, so some systems automatically remove empty folders].

Try creating this folder on your server: `/themes/default/cache/` - the cache folder was automatically removed because it's actually empty. 

I'm not sure this is the cause of your issue, but it's worth giving it a shot. I've patched the issue on the repo & it'll be in the next release.

**Comment by chakthy** [comment]
Hello
I did notice that and created the folder, I even copied the index file from the previous version cache folder, but I still have the same issue with the blank page. On Safari I get the blank page but on Chrome is showing the HTTP Error 500. Everything on the folder has the 777 permissions.

**Comment by chakthy** [comment]
It looks like there is a problem with the function mb_split on the Sessions.class.php
I commented the code on the /install.index.php and the page loads now. It will probably break later if there is a need of that code later in the installation or use of the program.

**Comment by benkeen** [comment]
Ahh! Thanks for debugging that. Yeah that's been reported here - #158 - I just haven't patched it yet. I should have time tomorrow night to get this fixed & a new beta out the door. I'll close this issue then. 

Thanks again!

**Comment by chakthy** [comment]
Thanks

**Comment by benkeen** [comment]
I just released a fresh beta (3.0.0-beta-20170315), plus updates to the Report Builder + Hooks Manager module. Just download the latest file here & let me know if you have any more trouble! https://formtools.org/download/
