### ISSUE TITLE
Problems upgrading to v3.0

### ISSUE THREAD

**Issue by dethompsowu** [formtools/core#184]
I have FormTools v2.2.6, but when I follow the upgrade instructions [here](https://docs.formtools.org/upgrading/) (specifically, step 3 in the "General upgrade instructions" section...I've already done the "Upgrading Steps" listed [here](https://docs.formtools.org/upgrading/3_0_0/)), the Upgrade screen that comes up says "Core - Your Version: 2.2.6, Newer Version(s) (No newer version)." All of the other elements on the page (the themes and modules) _do_ list newer versions. So when I click the "Generate Zipfile from Selected Components" button, the ZIP file _only_ contains a "themes" and a "modules" folder.

Needless to say, when I follow the rest of the [upgrade process](https://docs.formtools.org/upgrading/), I never get as far as step 6. When I access the FormTools login page, all that comes up is an empty page (it still has the FormTools theme header thing across the top, but there isn't a login box or anything.

Luckily, I was a good boy and backed up my files and database, so I was able to revert without a problem.

So what's happening? Is there a different way that I should be going about attempting the upgrade?

**Comment by paul4ttuhsc** [comment]
Exact same problem for me.

**Comment by paul4ttuhsc** [comment]
More info - I have both a 2.2.5 installation and also a 2.2.6 installation.  An update attempt from 2.2.5 DOES offer the 3.0.0 core upgrade in the ZIP download, but an update from 2.2.6 DOES NOT offer the 3.0.0 core upgrade.

**Comment by benkeen** [comment]
Sounds like there may be a problem with the zip files... I added in some "clever" caching so it wouldn't always regenerate the zipfiles every time they're requested; the drawback is that if anything is incorrect about them, it compounds the problem. I'll look at this tonight, apologies!

**Comment by benkeen** [comment]
Sorry, I didn't have time to look at this tonight. Do either of you have the zipfiles still handy that you downloaded for the upgrade? What was the filename of the one that failed for you? No worries if you don't have it - it would just make it easier to track down.

**Comment by dethompsowu** [comment]
Here is the ZIP file for the upgrade that was downloaded on my end: 
[FormTools_up1628.zip](https://github.com/formtools/core/files/1932277/FormTools_up1628.zip)

**Comment by paul4ttuhsc** [comment]
Here is my ZIP and [short vid](https://youtu.be/AYMMiygmBgA).



[FormTools_up1634.zip](https://github.com/formtools/core/files/1932460/FormTools_up1634.zip)

**Comment by benkeen** [comment]
Thanks for the help! I've just fixed this on the website. It was a combination of a glitch in the code and the caching mechanism for the generated upgrade packages containing the wrong code. I tried an upgrade from 2.2.5->3.0.0 and 2.2.6->3.0.0 and they're both working properly now, listing all newer versions of the core for download. 

N.B. There's another issue a few people have mentioned about the Field Types not being properly updated when upgrading which I'm going to check out now. So if you're not in a rush, maybe hang off until I release 3.0.1 (later today or tomorrow).

**Comment by paul4ttuhsc** [comment]
OK, attempting 3.0.0 -> 3.0.1 upgrade gives this error:

![formtools-error](https://user-images.githubusercontent.com/6989198/39135498-b33a1188-46de-11e8-9c59-c77900c632ec.png)

**Comment by paul4ttuhsc** [comment]
Likewise 2.2.6 -> 3.0.1

![formtools-elp](https://user-images.githubusercontent.com/6989198/39135645-03da6c8c-46df-11e8-8cb4-b6558c484a68.png)

**Comment by benkeen** [comment]
Drat, drat, drat. At a quick guess, it looks like possibly when you upgraded to 3.0.0, your modules, themes + API weren't updated - only the Core. That's now confused the upgrade script because the old version mapping of v3 core -> modules, themes & API are now invalid. But I'll need to check this out tonight to see how it behaves under these conditions.

If you want a quick fix, bypass the upgrade script altogether. The purpose of the upgrade script was  to *simplify* the process of upgrading all your components at once, but that's clearly not the case here. If you want to do that, download the main package here: 
https://formtools.org/download/ and just remove any modules you don't want (from the ./modules folder in the zipfile) then overwrite those files on your server. For additional modules that weren't in that package that you have, you'll need to manually download them from the appropriate repo:
https://github.com/formtools/ (under the "releases" section of the repo), then follow these upgrade instructions for each one:
https://docs.formtools.org/userdoc/modules/installing/

I'm really sorry this has proven to be such a headache. This is why FT 3.1 is devoted to revising the upgrade + installation code. The upgrade script is a nightmare to manage on many levels, but I *did* think it was solid.

**Comment by paul4ttuhsc** [comment]
It looks like for the 3.0.0 -> 3.0.1 upgrade my modules are already current (attached below). However, I have not yet actually attempted a 2.2.6 - > 3.0.1 update, so I'm not sure module mismatch is an issue with that upgrade (see last screen shot in my previous post).

![ft300-modules](https://user-images.githubusercontent.com/6989198/39138251-2829de32-46e5-11e8-9651-728f36ea66f9.png)

**Comment by benkeen** [comment]
Ah, thanks. I'm looking at it now.

**Comment by dethompsowu** [comment]
The upgrade performed as expected here on my end when I tried it a few minutes ago :)

**Comment by paul4ttuhsc** [comment]
I have updated both my servers successfully. Thanks a ton!

**Comment by benkeen** [comment]
No worries, sorry for the fuss and I appreciate the bug report!
