### ISSUE TITLE
PHP Fatal error:  Uncaught PDOException: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'email_reply_to'

### ISSUE THREAD

**Issue by deadpoint** [formtools/core#207]
Hi,

I'm getting the following PHP Fatal error when attempting to create a new email, and save the finished definition.

`
[Thu May 10 09:36:41.284749 2018] [:error] [pid 18030] [client 10.100.20.150:2430] PHP Fatal error:  Uncaught PDOException: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'email_reply_to' at row 1 in /srv/www/formtools/builder/global/code/Database.class.php:143\nStack trace:\n#0 /srv/www/formtools/builder/global/code/Database.class.php(143): PDOStatement->execute()\n#1 /srv/www/formtools/builder/global/code/Emails.class.php(967): FormTools\\Database->execute()\n#2 /srv/www/formtools/builder/admin/forms/edit/page_edit_email.php(20): FormTools\\Emails::updateEmailTemplate('2', Array)\n#3 /srv/www/formtools/builder/admin/forms/edit/index.php(122): require_once('/srv/www/formto...')\n#4 {main}\n  thrown in /srv/www/formtools/builder/global/code/Database.class.php on line 143, referer: https://domain.com/builder/admin/forms/edit/index.php?page=edit_email&form_id=1&email_id=2
`

The environment is:
Formtools-3.0.1-20180430
- Switftmail configured/enabled

SUSE Enterprise 12sp3
- apache2-2.4.23
- php7-7.0.7
- mariadb-10.0.34

For what it's worth, I have this working on a test system where the only difference is php5-5.5.14.

**Comment by benkeen** [comment]
Hey @deadpoint, sorry about that! This is due to MySQL strict mode being enabled on your PHP7 system. I'll post a fix for this tonight and release a new version of the core this weekend.

In the meantime, you should be able to get around the issue by adding this setting to your `global/config.php` file:

```php
$g_set_sql_mode = true;
```

It's a dreadfully named setting (I really don't know what I was thinking...) but that'll tell Form Tools _not_ to use strict mode for any database queries. It should get around your current problem.

But yeah, I'll patch this in 3.0.2 properly to remove the source of the error, and maybe think about adding a new config setting for more fine-tuned control over the SQL mode.

**Comment by deadpoint** [comment]
That fixed things, thanks!
