### ISSUE TITLE
Fatal error:  getModuleName() 

### ISSUE THREAD

**Issue by SvenPremier** [formtools/core#232]
Hello

after updating from 2.0.3 to 3.0.2, I can't access to Modules section:

Fatal error: Call to a member function getModuleName() on boolean in /homepages/1/d368702781/htdocs/clickandbuilds/FormTools/Form_Tools/admin/modules/index.php on line 55

Any idea?
Thanks
Xavier

**Comment by benkeen** [comment]
Hi Xavier, sorry for not getting back to you sooner. It sounds like perhaps all the files weren't uploaded to your server when upgrading. That's the usual culprit. I'd start there, by reuploading all the files.

If it's still an issue, on line 55 of the file, right before that line that complains, add the following:

```php
echo $module_info["module_folder"];
```

That'll let you know which module is causing the problem. We can go from there.

**Comment by SvenPremier** [comment]
Hi, 
sorry for my late reply. I reuploaded again and same message.
I added echo before line 55 and result is:
core_field_types
Thank you
Xavier

**Comment by benkeen** [comment]
Oh no problem! Take a look here under "Form Tools 3 changes":
https://docs.formtools.org/upgrading/3_0_0/

You'll need to delete the `/core_field_types` folder in your `/modules` folder in order to upgrade. Sorry, the doc should have been clearer there & this should have been placed under the upgrade instructions section. That module has been incorporated as part of the Core in 3.0.0. 

Also apologies: this scenario should be handled better in the code and not just throw an error.

**Comment by SvenPremier** [comment]
Hi,
thanks for your support; it works fine now!
