### ISSUE TITLE
Searching with Chinese character will occur an error.

### ISSUE THREAD

**Issue by wkl17** [formtools/core#252]
When I search with Chinese character on the page /admin/forms/submissions.php?form_id=1 
, an error will occur :
------------------
Uh-oh.

The system encountered a serious database error. This should not occur. Please report these details in the Form Tools forums.

Class: FormTools\Submissions
File: /www/wwwroot/mysite/global/code/Submissions.class.php
Line: 1072
Error: SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation 'like'
-----------------
Form Tools Version: 3.0.2
服务器： Localhost via UNIX socket
服务器类型： MySQL
服务器版本： 5.5.54-log - Source distribution
协议版本： 10
用户： mydatabase@localhost
服务器字符集： UTF-8 Unicode (utf8)
nginx/1.12.1
数据库客户端版本： libmysql - mysqlnd 5.0.10 - 20111026 - $Id: c85105d7c6f7d70d609bb4c000257868a40840ab $
PHP 扩展： mysqli 文档
PHP 版本： 5.4.45

**Comment by benkeen** [comment]
Thanks @wkl17! This is a bug. I'll address it in the next release.

**Comment by benkeen** [comment]
Sounds like this was due to a MySQL bug. It doesn't permit searching datetime fields with utf-8 chars. Since it's actually kind of nice being able to include date fields with the "All fields" searches, what I've done is detect to see if the search string contains any characters that would never appear in a datetime field (namely anything but `0-9`, `:` and `-`) and omit those fields. That'll avoid the issue but keep the same functionality as now.

I've been struggling to find time these last few weeks but I should get 3.0.3 finished by the weekend that'll include this fix.
