### ISSUE TITLE
3.0.2 upgrade issue - Slow file exporting

### ISSUE THREAD

**Issue by tkelling** [formtools/core#270]
Hi,

Thanks for the great application!

We recently upgraded to 3.0.2 and are having a persistent problem. I've tested on two completely different servers and have had our server team look into it. Seems to be an issue with the application.

The main issue is that database exports are very sluggish compared to past versions of Formtools. This causes usability issues and crashes our server because it times out. These export processes take 10 times or more longer than they did on the Formtools v2. This issue seems to be most apparent on databases with more than a few hundred or over a thousand entries.

I've noticed similar sluggishness on the preparser module. Our list of rules are very slow to appear when working with this module. This is less of an issue, because we don't use it much, but this might be related.

Any suggestions for speeding up the file exporting?

Everything else with the upgrade appears to be working as expected.

tlk

**Comment by benkeen** [comment]
Hi @tkelling,

Thanks for letting me know. For the exporting, that sounds very possibly just a performance issue with the Export Manager module. When I refactored it for 3.x it's possible I changed something or introduced some sort of problem that would slow it down. Exporting is typically a very slow process because there's so much code involved, so even a small mistake slowing down a small part of it could have big ramifications. I'll take a look. 

But the Submission Pre-Parser module being slow is a puzzler, I must admit... I see you've opened an issue on that repo about this - thanks for that. 

I'm _finnnnally_ going to be getting more time to work on Form Tools again in the next little while so after the 3.0.3 release I'll take a look at both of these. 

Thanks!

**Comment by tkelling** [comment]
Great. Thank you! Let me know if I can provide any more information.

**Comment by benkeen** [comment]
Hi @tkelling, sorry for the wait. 

I've re-enabled a cache option used in FT2 which was removed in FT3. I'll include it in 3.0.4 which I'll release later today.

On my own tests it definitely improves performance, but benefits will depend upon how many Option Lists you have defined and how many options they contain. For a form with no option lists, there will be no speed improvements at all, but for form with larger numbers of checkbox/radio/dropdown field with lots of options there should be a very noticeable improvement. 

On my own tests of 2 option lists with 30 items in each, generating 1,024 rows went from 18 seconds down to 14 - and pretty reliably. Hopefully this'll help.

**Comment by tkelling** [comment]
Thanks! That's great news.
