### ISSUE TITLE
database structure changes

### ISSUE THREAD

**Issue by jacobidiego** [formtools/core#315]
Hi folks,
I have added some columns to the database of each ft_form_x with data that is automatically added from my statistical system in php.

I now need to delete a column from the original columns and I wonder, If I make any change from formtools interface, of deleting or adding new fields, if it would break the database structure.
How can I see the SQL command before it is executed?
Will it delete columns that it doesnt know about?

**Comment by benkeen** [comment]
Hey @jacobidiego, hmm... I think it just prunes the database table to remove the columns individually, so you should be fine. I'm afraid there isn't a way to view the SQL query prior to it being executed (neat idea though).

If I were doing this myself, I think I'd create a separate table to store the custom fields - e.g. `ft_form_X_custom` and then have a 1-1 map of the submission ID in one table to the submission ID in the other. That way there would never be any possible conflict of with Form Tools code. Drawback, of course is that you'd need to add various hooks so that deleting from the source table would also delete from the origin one. Or you could just hook up a task to remove old data on a scheduled task/cron.

**Comment by jacobidiego** [comment]
Hi @benkeen.
So if I remove a field of user data from formtools will it only remove that column or will it do a full rebuild which can potentially erase unknown columns for formtools.

**Comment by benkeen** [comment]
Hey @jacobidiego, it just removes that single field and leaves the other fields intact:
https://github.com/formtools/core/blob/master/global/code/Fields.class.php#L1515-L1517

**Comment by jacobidiego** [comment]
Thank you.
The reason why I need to do.
Tested and worked !!

Is there any chance for formtools to be able to handle INTEGER columns in the database?

**Comment by benkeen** [comment]
Hey @jacobidiego - sorry, I missed this follow-up question. At this point no, Form Tools only supports varchar fields. I've toyed with the idea of adding other types but nothing on the radar yet.
