### ISSUE TITLE
I'm getting this "The form field 'field89' could not be added.", can someone help me?

### ISSUE THREAD

**Issue by dropej** [formtools/core#328]

**Comment by benkeen** [comment]
Hi @dropej,

Where do you see that error appear? Could you share a screenshot? Generally here are two likely causes:
- PHP configurations on servers sometimes have a limit of the number of fields that can be in a single POST request.
- Database tables can only have a certain number of VARCHAR fields. If you're adding one of those, try changing it to "Text" and see if that makes a difference. 

Ben

**Comment by dropej** [comment]
Thanks for the quick reply.
Here the screenshot (it is on the Form Builder) 
![image](https://user-images.githubusercontent.com/6913715/46086060-5b2fe500-c175-11e8-9e30-2ab7c22707d3.png)

**Comment by benkeen** [comment]
Ah cool! If it turns out there are PHP limitations in place, you can easily get around it on this page by changing the "Show X fields" setting on this page to show a subset of the fields. N.B. I'll be revising the interface of this page in Form Tools 3.2 so PHP POST size limitations will be much less of an issue.
