### ISSUE TITLE
System Check Module - Table Verification Hangs, Doesn't Run

### ISSUE THREAD

**Issue by flcowboy7** [formtools/core#410]
After upgrading from 2.2.5 -> 3.0.0, the Table Verification (System Check Module) gets stuck and never runs. This persisted through when upgrading from 3.0.0 -> 3.0.9. Below are the environment details and a stack trace from the PHP error log.

**ENVIRONMENT OVERVIEW**
Form Tools Core Version: 3.0.9
Core Version Upgrade Track: 2.1.8,2.1.9-main-20111206,2.2.0-main-20111231,2.2.1-main-20120206,2.2.2-main-20120301,2.2.3-main-20120423,2.2.5-main-20120503,2.2.6-main-20130629,2.2.5-main-20120503,2.2.6-main-20130629,2.2.5-main-20120503
API Version: 2.0.0
PHP Version: 5.6.39
MySQL Version: 5.6.41
PHP Sessions: Available
Suhosin Extension: Not Installed
Curl Extension: Available
SimpleXML Extension: Available
____________________________________
MODULES (name, version, enabled)
Core Field Types, 1.0.2, No
Export Manager, 3.0.5, Yes
File Upload, 2.0.2, Yes
Pages, 2.0.6, Yes
Submission History, 2.0.4, Yes
Submission ID Manager, 2.0.1, Yes
Submission Pre-Parser, 2.0.4, Yes
Swift Mailer, 2.0.6, Yes
System Check, 2.1.3, Yes
TinyMCE Field, 2.0.7, Yes
____________________________________
THEMES (name, version, enabled)
Default, 1.0.0, Yes

**PHP ERROR LOG**
_**obfuscated for security reasons**_
`[19-Dec-2018 22:33:19 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-name' at line 1' in /home/user/public_html/formtools-name/global/code/Database.class.php:71`
`Stack trace:`
`#0 /home/user/public_html/formtools-name/global/code/Database.class.php(71): PDO->prepare('SHOW TABLES FRO...')`
`#1 /home/user/public_html/formtools-name/global/code/General.class.php(97): FormTools\Database->query('SHOW TABLES FRO...')`
`#2 /home/user/public_html/formtools-name/modules/system_check/code/Tables.class.php(39): FormTools\General::checkDbTableExists('ft_account_sett...')`
`#3 /home/user/public_html/formtools-name/modules/system_check/code/actions.php(55): FormTools\Modules\SystemCheck\Tables::checkComponentTable(Array, 'ft_account_sett...')`
`#4 {main}
  thrown in /home/user/public_html/formtools-name/global/code/Database.class.php on line 71`

**Comment by benkeen** [comment]
I checked my notes in the Upgrade code and it does appear that it's a safe upgrade from 2.2.5 to 3.x, so you're probably okay. 

Regarding this issue posted here, have you noticed any other issues with the application yet? Hmm... It's kind of hard to debug - even with a stack trace. It seems the `SHOW TABLES FROM ...` command is throwing an error, which probably means there's a DB connection issue rather than a problem with the SQL itself (it's a pretty basic command...). Still, if you have DB access you could try running that command just to confirm it works. 

I'm awfully sorry, I'm really not sure what to suggest for debugging without going line by line in the code. 

If you fancy, email me at ben.keen@gmail.com with temporary FTP into & instructions on how to see the problem, and I can debug it there. (But I may not be able to get to this until Saturday, note).

**Comment by flcowboy7** [comment]
I gave you access. I *DO* have access to the DB, but not sure how to run commands using phpMyAdmin... If you give me specific instructions, I can definitely run it, though.

**Comment by benkeen** [comment]
Thanks @flcowboy7, I appreciate the access. I've logged the following but on the System Check module and will release a new version containing the fix later today. Thx!

https://github.com/formtools/module-system_check/issues/9
