### ISSUE TITLE
Have SSL Form Tools forms not showing lock in browser

### ISSUE THREAD

**Issue by barrydollar** [formtools/core#445]
Checked on why no padlock site and all the issues are the domain written in the scripts not including the 's' on 'http'. I do not code and not sure how to begin to resolve these issues. Any help would be much appreciated.
See errors here:
https://www.whynopadlock.com/results/68f7f466-37de-4b6d-8c46-0318405d144c
https://www.whynopadlock.com/results/b834e140-38e0-4c38-b32b-0abbde169977

**Comment by benkeen** [comment]
Hey @barrydollar, did you figure this one out? I looked at the errors and they're all due to resources being loaded from the `http` protocol not `https`. I'd take a glance but it looks like your form is now down. Form Tools uses either relative paths or the value of your `$g_root_url` setting in your `global/config.php` file to construct the URLs, so I'd check that file if this is still an issue.

**Comment by barrydollar** [comment]
So right after I posted this the site went down for other reasons. It is now back up. Yes I do understand the paths that are missing the 's' on http. So would I open the global/config.php and change the $g_root_url  value to "https"? Do I do this in the cpanel or via FTP?

**Comment by barrydollar** [comment]
OK. Updated it in the cpanel and all is working now. Thank you benkeen!
