### ISSUE TITLE
File Uploading

### ISSUE THREAD

**Issue by mahbgithub** [formtools/core#448]
Hi,
I'm using formtools for Applications. All applicants have to upload their CV. It's not really a problem but might be a security risk, as all files are uploaded to the same location and just renamed in case a similar file already exists.
That means I have many files with following formating:
CV.pdf
1_CV.pdf
2_CV.pdf
That means more or less, if someone known formtools he can guess the file location and name.
It would be great to have a possibility to rename all uploaded files fore example like:
ID_FirstName_Lastname_Date.pdf
Thanks
Martin

**Comment by nelsondcosta23** [comment]
Sounds a nice ideia.

**Comment by benkeen** [comment]
Hey @mahbgithub, I actually had a little time today and got this feature working. 

I couldn't add the user placeholders you wished for, since files can be uploaded via the module from all sorts of locations, including anonymous forms. But I did add the following placeholders:
- `{$submission_id}`
- `{$form_id}`
- `{$clean_filename}` (filename with all non-whitelisted chars stripped out - this is the current )
- `{$extension}` (the file extension)
- `{$date}` (YYYYMMDD)
- `{$unixtime}`

The last one can be used to output a date / time in any format, by passing a modifier: `{$unixtime|date_format:"Mj Y"}

I'm just putting the finishing touches on it and writing up the documentation, but I'll release the update this weekend. Going to close this ticket & commit against the other one on the File Upload module linked above.

**Comment by benkeen** [comment]
Added in 2.2.0. See: https://docs.formtools.org/modules/field_type_file/filenames/

**Comment by mahbgithub** [comment]
Hi,
I very much appreciate your help here. Today I updated formtools and the module.
What I actually ment is, that I have a form which is asking for:
- Upload file
- First Name
- Last Name
- Birthday
and then the file is renamed to:
- First Name.Last Name.Birthday.{$extension}
I hope my attached screenshot is hown.
Many thanks again
Martin
![file_upload](https://user-images.githubusercontent.com/26004567/52345294-1cf8db00-2a1d-11e9-9095-6fec7fde68b3.jpg)

**Comment by benkeen** [comment]
Hey Martin, 

I'm afraid these are the only placeholder available: https://docs.formtools.org/modules/field_type_file/filenames/

You can't currently access string values from fields in the submission itself, like Birthday, name etc. 

Sorry about that! But feel free to put in a feature request here, and I'll hopefully get to it at some point: https://github.com/formtools/module-field_type_file/issues

Ben
