### ISSUE TITLE
[BUG] Field date is cleared if file field not pass verification

### ISSUE THREAD

**Issue by stfour** [formtools/core#475]
Hi Benkeen, I've found another minor issue. If you have in the form some text fields, a date field and a file field, if file field do not pass verification (for example bad extension), all fields are retained but not the date. You have to reinsert it.

Thank you

Marco

**Comment by benkeen** [comment]
Ah, I see. So this is actually a very old bug - nice find! 

I'm just going to jot down my findings so I have something to work off when I fix this. 

The problem is this: in case of a failed submission update, there's a method (`FieldValidation::mergeFormSubmission()`) that merges together the content of the POST request with what was already in the database. The intention is that it shows as much of the new submission data as possible, even if something failed to get updated. 

However for fields like phone number fields and date fields, that merge method is incorrect. The content of the POST submission contains the data in a format that's incompatible with the field when the page re-renders, which is why you see a blank field. 

So really we need two fixes:
1. we need to differentiate a "true" failed submission update from a file upload error. The latter means we can just show all the latest data from the database, since we know it's been updated. The former means we'll need to do the merge submission like now. 
2. Fix the merge submission method to handle the phone + date field types.

The first one is straightforward to fix, the second one is exceedingly difficult - and compounded by the Custom Fields module. 

I've pulled this out of 3.0.13 but I'll address it at some point.

**Comment by stfour** [comment]
Wow, thank you for the deep explanation!

Thank you!

**Comment by benkeen** [comment]
No problem! Actually this issue should be easier to solve now that 3.0.13 is out. I'll try to get it into an upcoming release.
