### ISSUE TITLE
Any precautions to take after using Form Backup?

### ISSUE THREAD

**Issue by lolekbolek20** [formtools/core#485]
Greetings!

I copied a form using Form Backup, so I have an identical copy in the list of forms and I can see a new frm_form_2 table created in phpMyAdmin.  The only thing that I would like to clarify is whether I need to do something manually to make sure that nothing happens to one of the forms if I delete the other, as described here: [https://docs.formtools.org/modules/form_backup/].

> By and large, the module's functionality and usage speaks for itself: but there is one possibly unexpected behaviour you should know about.

Files
Form Tools stores files directly on your server in a folder, not inside the database. The database only stores the filenames. So, when you make a backup of a form, the files are NOT copied: both forms will then refer to the same file. If you delete a file from one form it will "orphan" it from the other. In other words: the other form will still contain a reference to it, even though the file doesn't exist.

Similarly, if make a backup of a form then delete the original one and choose to delete all the uploaded files, the backed-up form will only contain references to the deleted files.

**Comment by benkeen** [comment]
Hey @lolekbolek20, sorry for not responding sooner - trying to get 3.0.13 out the door...!

> The only thing that I would like to clarify is whether I need to do something manually to make sure that nothing happens to one of the forms. 

The only thing you need to worry about is the files. When deleting the original form, it'll present you with an option to choose whether or not to delete the associated files. You'll want to NOT delete the files, otherwise the backed-up form will show links to the now-deleted files in the interface when browsing.

What we really need, btw, is an option in the Form Backup module to copy over all the files as well. Feel free to add a feature request on that module.

**Comment by lolekbolek20** [comment]
Million thanks, Ben!  All clear now!

**Comment by benkeen** [comment]
No problem :)
