### ISSUE TITLE
During install MySQL available Yes FAIL

### ISSUE THREAD

**Issue by mactrash** [formtools/core#602]
I try to install formtool 3.0.15
and my Mysql is 5.0.95
I am stuck in the step2 during install
Can anyone offer some help about this?

Many thanks.

**Comment by mactrash** [comment]
@benkeen 
![Screen Shot 2019-08-28 at 3 31 56 PM](https://user-images.githubusercontent.com/1506388/63834977-1cb83100-c9a9-11e9-9081-beb279657109.png)

**Comment by mactrash** [comment]
@benkeen is that any hack can by pass this? I don't find any hack in this version.

**Comment by benkeen** [comment]
Hey @mactrash, sorry the inconsistent error/labels is a bug in the installation page: it should be saying "No" for the line that says FAIL. That page checks that you have the **pdo_mysql** extension running on your server. I'm afraid you'll need to get that installed in order to run Form Tools on your server. 

Sorry about that!

**Comment by graywen24** [comment]
same here.. i tried both docker and local server all show same as this... really no idae

**Comment by benkeen** [comment]
The incorrect error message has been fixed in the new installation script coming out in 3.0.16. However, note that the pdo_mysql extension will still be required to run the script.
