### ISSUE TITLE
Form tools not sending emails from form

### ISSUE THREAD

**Issue by useralp** [formtools/core#780]
I reinstalled FT 3.0.2 and created a new form.  I am able to successfully send test emails from the email test area.  The form is published.  When I submit on the actual from, it processes, adds a new submission to the data base, but does not send an email.  I am also getting an error when I click on the view submission link.    

I tried to set up swift mailer, but had no success with that.  It failed all test sends.   System check did not find any problems.

If anyone can point me in the right direction, it would be very helpful.

Thanks, Anatol

**Comment by rowright** [comment]
Hey There!

It sounds like the non-Swift emails are working for you. Swift Mailer is generally used when you have a SMTP server for sending email instead of using your servers built in email sender. If your going to be sending a large amount of email, I would recommend you look at Swift Mailer in more detail.

Since you're able to send test mails, I would recommend that you look next at your form's configuration for how emails are being sent. Emails are sent based on rules - so for example if a field condition is met on a submission or if they are only sent manually via UI.

Checkout this page for more information on configuring the Email Event Triggers. https://docs.formtools.org/userdoc/emails/emails_configuration_tab/

If you want, screenshot your email config page here and I can take a look (please blur out an PII or sensitive data in your screenshot however).

**Comment by useralp** [comment]
I was able to get it to work after several failed installations.  I am using swift mail and it works great. PS,   go daddy sucks...
