### ISSUE TITLE
Form Tools hasn't received a successful test submission yet

### ISSUE THREAD

**Issue by ervinmisso** [formtools/core#797]
I have this error on screen. I cant configure this or don't need who is file responsible for modification.
3. TEST SUBMISSION
XForm Tools hasn't received a successful test submission yet.
Here's where the fun starts! At this point, Form Tools is waiting for a test submission from your form. It will use this form submission to know what information should be stored in the database.
To help integrate your form, we suggest you read one of the following tutorials:

Adding a single-page form with the API
Adding a multi-page form with the API
They explain how to set up your form in preparation for the test submission, and include other information that may be of help. The line of PHP you will need is:

$fields = $api->initFormPage(1, "initialize");
On the page PRIOR to your final "thank you" page, be sure to add the following parameter to the $params variable:

    "finalize" => true
This ensures the data is actually sent to Form Tools. When you have put through your test submission, click the button below.

Awaiting form submission.

**Comment by ervinmisso** [comment]
where can fide this?
$fields = $api->initFormPage(1, "initialize");

**Comment by rowright** [comment]
Hey There!

What the line of PHP is referencing is on your actual HTML Form side. The page there is asking you to finish the setup of your form to talk to Form Tools.

Instead of using the API method to connect to Form Tools if you've not used the application before, it's easier to get started with the Form POST method. https://docs.formtools.org/userdoc/form_management/add_form_step3/

Form Tools allows users to send their HTML forms to the application in two ways - one using the browser based POST method (meaning when your form submits, you set the destination in your <form> tag in your page's HTML to Form Tools or via the PHP API which you call and load the API into the page and then have access to those variables).

If you're new to the application - check out this user doc on how to setup your form for the first time.
https://docs.formtools.org/tutorials/adding_post_form/

**Comment by ervinmisso** [comment]
> Hey There!
> 
> What the line of PHP is referencing is on your actual HTML Form side. The page there is asking you to finish the setup of your form to talk to Form Tools.
> 
> Instead of using the API method to connect to Form Tools if you've not used the application before, it's easier to get started with the Form POST method. https://docs.formtools.org/userdoc/form_management/add_form_step3/
> 
> Form Tools allows users to send their HTML forms to the application in two ways - one using the browser based POST method (meaning when your form submits, you set the destination in your
> 
> tag in your page's HTML to Form Tools or via the PHP API which you call and load the API into the page and then have access to those variables).
> If you're new to the application - check out this user doc on how to setup your form for the first time.
> https://docs.formtools.org/tutorials/adding_post_form/

Ok but can you tell me which is the file I need to edit?
thnx.

**Comment by ervinmisso** [comment]
![Untitled](https://user-images.githubusercontent.com/86106389/122751095-9cef0b00-d28f-11eb-8ecd-b754c48277f3.jpg)

**Comment by ervinmisso** [comment]
anyone help me? i do not understand much of php so i want someone's help. or I can give anydesk credentials to configure them.
