### ISSUE TITLE
Unable to download customised arvhive

### ISSUE THREAD

**Issue by Plemus** [formtools/core#827]
Hi
Since a few days, I have remark that, when you try to download the latest customised archive on https://formtools.org/build/, after validate the captcha and clic on "Generate Zipfile", you are redirect to https://formtools.org/build/generated.php That is normal. But when clic on download, you are redirect to a blank page whive this url and no download occurs. I've tried different kind of browser but not suuceed.
Please help
![Uploading 1234.jpg…]()

**Comment by benkeen** [comment]
Hey @Plemus, ack sorry! I just moved servers and the paths must have got messed up. I'll look at this this weekend & post back when it's resolved.

**Comment by Plemus** [comment]
Hi
The custom build download does not work any more.
Would you help please


Hey @Plemus, ack sorry! I just moved servers and the paths must have got 
messed up. I'll look at this this weekend & post back when it's resolved.

**Comment by benkeen** [comment]
*Really* sorry - this slipped my mind. It's my first priority when I'm off work. Apologies!

**Comment by benkeen** [comment]
Hi @Plemus, I've spent a few hours now trying to bring it back, but it's proving to be extremely problematic with the new hosting. So instead I think it's time to shut down the site entirely. This was going to happen at some point, I just didn't quite expect it so soon. But perhaps it's best to shut it down before even more problems occur due to its age.

Ben

**Comment by Plemus** [comment]
All is fine now.
Thank to you, Ben and your staff
Big Up
